### ISSUE TITLE
Cycle on/off recording

### ISSUE THREAD

**Issue by leewujung** [aidanjohnson/dt7816#11]
- [x] Allow user to define on/off duty cycle so that we can record sounds only from dusk to dawn (in parallel with #7)

**Comment by aidanjohnson** [comment]
My implementation of this feature is currently under development. So far it reads in a file of sunset/sunrise times for a specified daily period. A fixed duration for this cycle on/off feature can also be set. Need to (1) give the user the option to disable the cycle on/off feature and (2) add a parameter for a buffer in seconds before sunset and after sunrise as a margin of safety.
