### ISSUE TITLE
Basic file saving

### ISSUE THREAD

**Issue by leewujung** [aidanjohnson/dt7816#3]
- [x] Filename contains the starting time of recording
- [x] Allow prefix in the filename before starting time for flexibility

**Comment by aidanjohnson** [comment]
File format I've set up (of course it can be changed):

`<identifying prefix>_YYYY-MM-DDTHHmmssuuuuuuZ.aiff `

where YYYY=year, MM=month, DD=day, HH=0-24th hour, mm=minutes, ss=seconds, uuuuuu=(remaining) microseconds, Z=Zulu time (that is, UTC or GMT; this can be changed to local time easily, for example to PST with the Z becoming PST).

The time of the timestamp corresponds to the start of the recording and writing of the AIFF file. The prefix is required to be provided by the user. The file path is predefined in the code, but can easily be a user input. 

We will also need to figure out how to synchronise the local time on the board so the timestamp is helpful. So far I know that it can be manually sent in the command line. If we have broadband access to the web we can have it synchronise to the atomic clock at [NIST](https://time.gov/), etc.

**Comment by leewujung** [comment]
I think the syncing part should be included in the UI such that you sync the board to the laptop programmatically. The laptop is syncs to NIST or other time centers so it's convenient. I'll add this to under #14.

**Comment by leewujung** [comment]
> The time of the timestamp corresponds to the start of the recording and writing of the AIFF file.

@aidanjohnson Is the timestamp the start of recording or the start of writing AIFF file? or do you open an AIFF file before the recording and close it when all samples are collected or when user abort recording?

**Comment by aidanjohnson** [comment]
I agree on adding the time synch to #14.

The timestamp corresponds to the opening (start) of the input recording buffer stream (i.e., right before). A file is opened and closed later when the stream buffer to transferred to the ring buffer.

**Comment by leewujung** [comment]
All cleared, closing the issue.
