### ISSUE TITLE
LED indicator for basic multi-channel recording

### ISSUE THREAD

**Issue by leewujung** [aidanjohnson/dt7816#4]
- [x] LED indicators on the board are programmed to show successful multi-channel recording in progress
- [x] Documentation for different LED indicator patterns

**Comment by aidanjohnson** [comment]
As of now (2018-07-03 at 16h00), the LEDs indicate whether each channel is currently in the process of reading/writing (on for active and off for inactive). The lights turn off if the exit routine (defined by the protocol in the code) is engaged, particularly what we will call a fatal error (e.g., invalid and excessive samples per channel set by the samples per file parameter).

**Comment by leewujung** [comment]
> e.g., invalid and excessive samples per channel set by the samples per file parameter

This can be addressed in UI. Adding as a requirement in #14.
