### ISSUE TITLE
Testing workflow

### ISSUE THREAD

**Issue by leewujung** [aidanjohnson/dt7816#5]
- [x] Review testing theory so that testing can be done with rigor
- [x] Establish testing workflow: pull request --> testing --> integration
- [x] Make sure each major pull request is clearly written with testing objectives and procedure

**Comment by aidanjohnson** [comment]
@funnyabc: What is meant by workflow is the written procedures for pull requests and merging. That is, we should have only one person to go through and merge (me) commits in pull requests from contributors (you). Putting it all in writing limits conflict.

**Comment by funnyabc** [comment]
Here is the proposed workflow that I see would work out for this project.

Everyone will be on the master branch, but every time there is a new feature being added, it needs to be in a separate branch.

Each branch must be synched up with the master repository, so as to not cause many conflicts when developing and submitting pull requests. When a feature is ready to be added, the user must submit a pull request with the master branch and someone (currently designating Aidan) needs to verify the feature will be compatible. There will be a template that will be used to submit each request, which will be made by the end of the week.

**Comment by leewujung** [comment]
These sound good. Looking forward to the template!

**Comment by aidanjohnson** [comment]
@funnyabc
Here's the link for the issue, pull request, and contribution templates: https://github.com/aidanjohnson/dt7816/community

**Comment by funnyabc** [comment]
These are some templates I am using from Steve Mao, another GitHub user who created these. The templates are from the public domain and available to use by the general public.

The template is a question and answer style, with a description for each portion of the template. In addition, there is a section that describes tests that need to be conducted by the contributor that shows the feature works in the context of the entire project.

https://github.com/aidanjohnson/dt7816/tree/master/.github

Template source repo: https://github.com/stevemao/github-issue-templates/tree/master/questions-answers

**Comment by funnyabc** [comment]
The basic workflow will be defined as the following steps.

1. Create a new branch. (Ensure to keep this branch updated with master during the entire development process)

2. Develop the feature

3. Test the feature until all cases covered and can confirm that it does not adversely affect any other project featured

4. Submit issue stating change. Then submit pull request with that feature. (If any changes need to be made according to the verifier, make them and resubmit). Be sure to fill out the issue and pull request templates when doing so.
