### ISSUE TITLE
Revise simple command-line UI

### ISSUE THREAD

**Issue by leewujung** [aidanjohnson/dt7816#9]
- [x] Add option for fixed-time or continuous recording (linked to #8)
- [x] Is it possible to have LED indicator to show which mode the device is in while recording is in progress?

**Comment by aidanjohnson** [comment]
> Is it possible to have LED indicator to show which mode the device is in while recording is in progress?

Presently, the LED indicators light up when a channel is active/enabled during the recording cycle, and off when inactive. If a channel is not activated during a sampling period, it will not light up. This uses all 8 available LEDs.
